apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-java-webapp-ingress
  namespace: mavenproject
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: my-java-webapp
                port:
                  number: 80
